### ISSUE TITLE
inference problem

### ISSUE THREAD

**Issue by WanFeng123313** [likyoo/BAN#2]
Hello, why the png result after setting --show_dir is very strange, there is a "unchanged" and a white rectangular block, in addition to the partition result is not very good, what is going on?
![image](https://github.com/likyoo/BAN/assets/81793539/546f8f6a-214a-41c0-94f9-7ce09a654eaf)

**Comment by likyoo** [comment]
Please install the lastest opencd and mmseg. 
This is just a visualization problem caused by the pkg version 😄

**Comment by WanFeng123313** [comment]
> Please install the lastest opencd and mmseg. This is just a visualization problem caused by the pkg version 😄

Thank you very much, the problem has been solved after I reinstalled mmseg and opencv. In addition, I would like to ask you a question, if I do not test only inference, which part of the code should I change?

**Comment by likyoo** [comment]
I guess you want [this](https://github.com/likyoo/open-cd/blob/main/docs/inference.md)?

**Comment by WanFeng123313** [comment]
> I guess you want [this](https://github.com/likyoo/open-cd/blob/main/docs/inference.md)?

That's very kind of you, but I got this error after using the code in it. How should I solve it?

Traceback (most recent call last):
  File "/mnt/lvm_data/project/xyguo/code_dmx/BAN/predict.py", line 3, in <module>
    inferencer = OpenCDInferencer(model='configs/ban/ban_vit-l14-clip_mit-b1_512x512_40k_levircd.py', weights='/mnt/lvm_data/project/xyguo/code_dmx/BAN/work_dirs/ban_vit-l14-clip_mit-b1_512x512_40k_levircd/best_mIoU_iter_36000.pth', classes=('unchanged', 'changed'), palette=[[0, 0, 0], [255, 255, 255]])
  File "/mnt/lvm_data/project/xyguo/code_dmx/BAN/open-cd/opencd/apis/opencd_inferencer.py", line 41, in __init__
    super().__init__(scope=scope, **kwargs)
  File "/mnt/lvm_data/public/package/anaconda3/envs/BAN_env/lib/python3.8/site-packages/mmseg/apis/mmseg_inferencer.py", line 81, in __init__
    super().__init__(
  File "/mnt/lvm_data/public/package/anaconda3/envs/BAN_env/lib/python3.8/site-packages/mmengine/infer/infer.py", line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File "/mnt/lvm_data/public/package/anaconda3/envs/BAN_env/lib/python3.8/site-packages/mmengine/infer/infer.py", line 483, in _init_model
    model = MODELS.build(cfg.model)
  File "/mnt/lvm_data/public/package/anaconda3/envs/BAN_env/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/lvm_data/public/package/anaconda3/envs/BAN_env/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/mnt/lvm_data/public/package/anaconda3/envs/BAN_env/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DualSiamEncoderDecoder is not in the opencd::model registry. Please check whether the value of `DualSiamEncoderDecoder` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs

**Comment by WanFeng123313** [comment]
I set "from opencd_custom.models.change_detectors import dual_siamencoder_decode", and now the problem has been solved. Thank you very much for today, wish you a happy work!
