### ISSUE TITLE
KeyError when Test

### ISSUE THREAD

**Issue by cgy-01** [likyoo/BAN#7]
When I follow the steps to configure the environment and run Test, I get the error “KeyError: 'BAN_MLPDecoder is already registered in model at opencd.models.decode_heads.ban_utils'”, how do I fix it?

**Comment by likyoo** [comment]
try [this version](https://github.com/likyoo/open-cd/tree/f05e7fdfe1e0f9a9afa9d6c063ea03b43345226e) of opencd

**Comment by likyoo** [comment]
Please provide full error reporting information, or just use open-cd, which now supports BAN.

**Comment by XinzheGeng** [comment]
作者你好，我遇到了同样的问题，以下是完整报错信息：
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    import opencd_custom  # noqa: F401,F403
  File "/home/gengxz/projects/BAN/opencd_custom/__init__.py", line 1, in <module>
    from .models import *  # noqa: F401,F403
  File "/home/gengxz/projects/BAN/opencd_custom/models/__init__.py", line 2, in <module>
    from .decode_heads import *
  File "/home/gengxz/projects/BAN/opencd_custom/models/decode_heads/__init__.py", line 1, in <module>
    from .ban import BitemporalAdapterHead
  File "/home/gengxz/projects/BAN/opencd_custom/models/decode_heads/ban.py", line 13, in <module>
    from .ban_utils import BridgeLayer
  File "/home/gengxz/projects/BAN/opencd_custom/models/decode_heads/ban_utils.py", line 285, in <module>
    class BAN_MLPDecoder(BaseModule):
  File "/root/anaconda3/envs/BAN/lib/python3.8/site-packages/mmengine/registry/registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "/root/anaconda3/envs/BAN/lib/python3.8/site-packages/mmengine/registry/registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'BAN_MLPDecoder is already registered in model at opencd.models.decode_heads.ban_utils'

另外，我尝试了在test.py中直接import opencd，会有以下报错：
Traceback (most recent call last):
  File "test.py", line 115, in <module>
    main()
  File "test.py", line 108, in main
    runner = Runner.from_cfg(cfg)
  File "/root/anaconda3/envs/BAN/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/root/anaconda3/envs/BAN/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/root/anaconda3/envs/BAN/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/root/anaconda3/envs/BAN/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/BAN/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/anaconda3/envs/BAN/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DualSiamEncoderDecoder is not in the opencd::model registry. Please check whether the value of `DualSiamEncoderDecoder` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by likyoo** [comment]
使用这个版本的open-cd作为依赖：https://github.com/likyoo/open-cd/tree/f05e7fdfe1e0f9a9afa9d6c063ea03b43345226e

或者直接使用最新版的open-cd

**Comment by XinzheGeng** [comment]
> 使用这个版本的open-cd作为依赖：https://github.com/likyoo/open-cd/tree/f05e7fdfe1e0f9a9afa9d6c063ea03b43345226e
> 
> 或者直接使用最新版的open-cd

感谢，已通过直接使用open-cd中的BAN解决
